tasks:
  - task_name: task-1
    build:
      mode: module
    lint: 
      mode: module
      module_options:
        configs:
          - config_path: 
              path_type: common
              path: task-1/.golangci.yaml
            required: true
          - config_path: 
              path_type: module
              path: .golangci.yaml
            required: false
    test:
      mode: module
      module_options:
        include_dirs:
          - path_type: common
            path: task-1/tests